### ISSUE TITLE
Remove RxSwift dependency into an external custom implementation of the Store

### ISSUE THREAD

**Issue by Aleksion** [Aleksion/reduxSwift#1]
Currently the store utilizes RxSwift to add, manage and dispatch to subscribers. While this gives us the whole range of RxSwift functions for free it might make sense to remove this dependency and create an optional store implementation in an external repository instead.

**Comment by agentk** [comment]
Hey @Aleksion,

I've been tinkering around with this idea too. I've separated out enough to be able to use RxSwift / SwiftBond as separate framework targets providing createStore functions, as well as a SimpleStore that just uses a trimmed down version of Bond internally.

RxSwift / Bond / ReactiveCocoa could then be seperate projects that reduxSwift.

I did mess up the Store in the process though. Would you be adverse to just providing one concrete TypedStore that's genericised from Store? Are there situations where a TypedStore would not fit?

I know an example would help, I'm cleaning it up now to push to my fork.

**Comment by Aleksion** [comment]
Hi @agentk ,

That's awesome! I'll be at my computer tonight, so I'll be ready to look through anything you have.
My intention was to move the rxSwift dependency to the reduxSwift-rx project. So that one has it's own implementation of the createStore function. We could do the same for bond. 
Optimally I would like to keep this project as dependency free as possible - and then make it very extensible (like the original redux)

What do you mean by one generic store? Previously store was generic, and there was no TypedStore. I really preferred that - but since typealias does not support generics, it made all the code extremely hard to read (all the nested functions had to show their actual return types rather than just typealiasses -> it gets messy)- 
So to improve readability for anyone wanting to contribute to the project, i made the whole thing work with any and then just introduced a generic typedStore.

I am, however, very open for suggestions regarding this. Cause i do dislike the whole "typedStore" thing :)

Let me know what you think

**Comment by agentk** [comment]
I've got most of the separation scaffold committed without changing the store. I think I'll keep working on it more tomorrow.

The primary layer between reactive libraries is now a StateStream struct that can be subclassed as RxStateStream for example. Then fed into createStreamStore.

I still have to move the internal EventProducer into a seperate framework target. I've left it there for now to keep tests working. I would probably be best replaced with a TestStateStream the does the worst job ever but just enough to pass tests.

To get my head around generics better, I wrote basic generic store tests and decided to see how I would pass them. The only main differences were in the store types and store creator:

``` swift
public func createStore<T where T:State>(reducer reducer: (T?, Action) -> T, state: T?) -> TypedStore<T> {}

public protocol Store {
    typealias StateType: State

    var dispatch: Dispatch { get }
    var subscribe: (StateType -> ()) -> Disposable { get }
    var state: StateType { get }

    init(dispatch: Dispatch, subscribe: (StateType -> ()) -> Disposable, getState: () -> StateType)
}

public struct TypedStore<T where T:State>: Store {
    public typealias StateType = T

    public let dispatch: Dispatch
    public let subscribe: (T -> ()) -> Disposable
    public var state: StateType { return getState() }
    let getState: () -> StateType

    public init(dispatch: Dispatch, subscribe: (T -> ()) -> Disposable, getState: () -> StateType) {
        self.dispatch = dispatch
        self.subscribe = subscribe
        self.getState = getState
    }
}
```

Using createStore as the source of generic types then made using the store a lot cleaner.

**Comment by Aleksion** [comment]
Regarding the store: Ha, if that works then it's great. It's been some time since I fiddled with this part. I suppose my problem was, that I defined getState on the Store protocol - and that the implementations didn't accept T as return type but needed something adhering purely to the type. fixing that with a state property is neat.

If you can get it to work, then I suppose we rename things, so the struct, that we're actually working with is called Store - and then we rename the protocol to StoreType. 

I'm looking forward to see your work on the createStreamStore.

**Comment by agentk** [comment]
Interesting. I hadn't thought about the issue of getState implementations.

I've split out the test / simple streams into the test target only now. Which means my fork is now useless without supplying a stream implementation. I'll see if I can get the stream store up and running over the next couple of days using a simple wrapper without seperate projects.

P.S. I had never thought of using structs as a group of functions. It fits really nicely into FP. I've been finding it very useful since I saw you use it in the Store. :-)

**Comment by Aleksion** [comment]
Well, I owe much of the credit to Dan Abramov and redux in general! 
But forcing myself to port it to swift made me realize some new and interesting ways to use the language.

**Comment by agentk** [comment]
I'm really sorry, but I got a bit heavy handed with paring down the code base. I'm not sure if you will want to merge any of it as it will take some level of rewriting existing code.

Notes:
- Reactive framework support is fully split out and can be used reasonably easily without extra frameworks
- State is now fully genericised
- The new store is Store: StoreType and expects state and disposable generic types
- Middleware are now just dispatch wrappers (example in tests for re dispatch)
- Example in tests for using ReactiveKit
- Generics are used a LOT in the SwiftRedux code, and very little in the client code

Creating a StateStream provider is now pretty simple:

``` swift
func createReactiveKitStream<State>(state: State) -> StateStream<State, DisposableType> {
    let observable = Observable(state)
    return StateStream(next: observable.next, observe: { observable.observe(observer: $0) }, latest: { observable.value })
}
```

Creating a store is simple too:

``` swift
store = createStore(createReactiveKitStream, reducer: applicationReducer, state: nil)
```

I've only just got it working I should add more comments and examples in the readme, but hopefully the code is fairly easy to understand.

**Comment by agentk** [comment]
Now for a bit more cleanup. I've removed the ReactiveCocoa dependency and created a seperate repo of tests that implement SwiftRedux examples with:
- SwiftBond
- ReactiveKit (successor for SwiftBond)
- RxSwift
- ReactiveCocoa

Each test has a readable example of creating a StateStream and a compact (isolated) example.

I could clean up the examples even more by removing the common Disposable if I didn't just make all the tests work by inheriting from a common set.

See: https://github.com/agentk/ReduxKitExamples

**Comment by Aleksion** [comment]
I like it!
I suggest we create and make an implementation of the RxSwift stream in the redux-rx project. 
Besides that, could we make a createStore function that does NOT take a stream? (and thus just use the default implementation). That might be what you've done, but I couldn't really deduct that from the examples.

Could you test your implementation with the reduxSwift-rx project? The tests have an observable action, which is asynchronous by nature. I just want to be sure that the applyMiddleware function still works properly with async calls (I made a mistake in my original implementation).

Looking forward to see your implementation.

When I have a little more time on my hands, I plan to start on the devtools - one of the more essential parts of redux. Let me know if you want to pitch in on that one.

**Comment by agentk** [comment]
Good idea on the createStore. Now that it's all split out, I was thinking about only providing a createStreamStore from reduxSwift and providing createStore from each of the implementation packages.

ie:

```
import RxSwift
import SwiftRedux // -> Can be used with anything that can create a StateStream
import SwiftReduxRx // -> Provides the createStore pre-built with an RxSwift StateStream
```

I'll try and tackle the reduxSwift-rx package first. I like the idea of the observable action. It should all still work out of the box ...... once I fix up the middleware definition that I oversimplified.

Quick question on the Redux way of things:

Should middleware each receive a reference to the outer most Store or just the Store + middleware at their level?

Ie, If I apply a ReTravelMiddleware first, then a RemoteMiddleware, should Actions dispatched from ReTravel only enter from it's middleware in, or should they enter the outermost store and pass through the RemoteMiddleware too?

I have currently removed the store from being passed in to middleware by the applyMiddleware function because I could see it leading to issues with re-travel as above (and because an trying to treat stores as immutable objects too). Instead opting for a more explicit way of passing in the store and any other middleware requirements.

Ie:

``` swift
store = applyMiddlewares([
    remoteMiddleware(api) { store },
    reTravelMiddleware { store }
    ], store: createTestStore(applicationReducer, state: nil))
```

How close were you wanting to stick to the Redux implementation, naming, usage?

I've taken the redux.js as guide and tried to apply the methodology in a natural way with swift. I can try and make functions work exactly the same as redux.js if you want. But I do like the way swift makes some things like middleware and immutability simpler (even if the generics were a bit mind bending to start with). Up until now I had not thought about it much though.

**Comment by agentk** [comment]
So..... Today I read through the Redux.js docs and source and have tried to make it as close as possible to Redux.js now.

I'm getting closer to your original implementation now too 👍. It's almost a drop in replacement again.

I haven't had a chance to look at reduxSwift-rx or redo the my example repo yet. But the internal tests are all passing again. They will have to wait for tomorrow.

✔️ Middleware: Now matches you original, just generic now. Should work out of the box for reduxSwift-rx. I've renamed applyMiddlewares to applyMiddleware to match Redux.js.
✔️ createStore: Now creates a simple store that can be observed. To create a store with a custom StateStream we can now use createStreamStore (which also defaults to SimpleStateStream if one is not specified)

Store & StateStream parameters now all match Redux.js too.

Most function types are now pretty scary looking because of State being generic, but as you can see from the tests, it's very simple to use.

**Comment by Aleksion** [comment]
Sounds great!
I'll get back to your previous question, but yes - each middleware should have the complete store object - and the current dispatch.If they don't have the complete store object, it will be impossible for asynchronous actions to trigger new actions that travel the middleware chain when they are fired. 
Sounds great! I'd like to stick as close to te original implementation as possible - to make it auper friendly for new web developers. That's also why i opted out of using classes which is seen in one of the other swift implementations.
Maybe we should keep the non generic type aliases and implementations in the code - out commented. I know it might mess up the files a bit, but reading the functions without them make them very hard to reverse engineer (i originally made them generically). The question is: would you have been able to contribute like you've just done without the readability it added?
I like to focus on the usage and consumption of the framework - but having the comments might help us get more contributors.
Let me know what you think

I look forward to trying it - i'll add a todo to the readme so we can discuss any further additions that we might add together.
Thanks for contributing!

**Comment by agentk** [comment]
+1 to everything.

Barrier to entry is a REALLY good point. I would not have been able to get this far without seeing StoreCreators in the original code and we should make it as easy as possible to maintain.

I've added internal specialised examples to the code now. I've used real specialised code to ensure everything still compiles and have just made the examples private with an underscore prefix. It's private, so we can change it as we like. Is it similar to what you were thinking (perhaps in a more concrete way)?

**Comment by Aleksion** [comment]
Sounds like what I have in mind! :+1:

**Comment by agentk** [comment]
I've updated the framework examples again. Split each framework out into it's own test target. Bit cleaner now.

And I've tested reduxSwift-rx. I pointed carthage at my repo for reduxSwift, update, compile and tests are passing without any code changes!

I guess the next step is to add OS X targets and tests. Then take the examples and turn them into seperate modules? Then documentation and devtools?

Also out of curiosity, how would feel about dropping the word swift from the built target? Similar to SwiftBond. This would also match the redux.js project then, both in code and name. Or another alternative is ReduxKit, following ReactiveKit and PromiseKit.

It's not going to get much smaller than three imports, but we can make it as easy as possible. Ie,

``` swift
import ReactiveKit
import Redux
import ReduxReactiveKit

let store = createReactiveKitStore(applicationReducer, store: nil)
```

**Comment by agentk** [comment]
Ps. Adding Redux to the iOS apps I work on is making them really clear and easy to work on 😊. It feels like I'm cheating.
I'll think about building a todo app as an example of how to use Redux, but it's not high on my priority list at the moment.

**Comment by Aleksion** [comment]
Sounds really great!

Well, we could do it for OS X - or focus on perfecting it for iOS development. I'm leaning more towards the latter.

I'll be most pleased about dropping the word swift - Lets just call it Redux in the code. I just hate renaming xCode projects :D.. 

I'd rather that people import a little extra, than us including libraries that people do not necessarily want to use in the project (like I did with RxSwift).

As soon as you're ready submit a pull request. 
If you like, you can add a TODO to the readme. 
I suggest we focus on the following:
- Create the TODO app. (we really need to showcase how easy it is) (I'm also using it for a project, and I love working with it. But it's a rather complex app that doesn't work very well as an example)
- Documentation : How thorough should we do it? The core principles are very well described by Dan in his docs (that's what enabled me to make this in the first place)
- Devtools - I feel this is where the power of redux really shines - being able to undo states when testing will make developing and debugging so much easier.

For me I also plan on finishing the reduxSwift-router (I hate storyBoards and like to do everything in code - and with this and something like Neon it's not only possible, but awesome to code in once you learn it. It feels like web development.

**Comment by agentk** [comment]
Hey @Aleksion,

PR #5 submitted. I'm not sure if you hate renaming Xcode project because of philosophical or technical reasons, but I ended up renaming everything to Redux.

I've also added targets and tests for OS X, tvOS and watchOS. This did not require any code changes, just additional targets. (And it works too!)

I've also added a podspec for issue #4. I would suggest maybe moving the project to a github organisation first, such as SwiftRedux/Redux. It will require some work in updating references to the project, but with the framework you've built, you deserve it.

I've also started adding documentation about the StateStream, API's and the generics issues to the readme.

Next up: To publish the reactive framework bindings and an example todo app. 🤓

**Comment by Aleksion** [comment]
Basically it tends to mess up my projects technically ;)... So great that you did it!
I'll have time to review and test the code. If everything works as intended, we're good to go (which it definitely sounds like it does!)

thx for taking care of #4 as well. Makes it easier for people to use it.

I like the Idea of transferring it to a organization account. I wouldn't mind having this become a community project - I'm just glad to be a part of it. I'll look into that as well. Need to fix the depending frameworks as well then.

**Comment by agentk** [comment]
I've pushed the binding up now too and they are ready to transfer.

https://github.com/agentk/ReduxRx
https://github.com/agentk/ReduxBond
https://github.com/agentk/ReduxReactiveKit
https://github.com/agentk/ReduxReactiveCocoa

**Comment by agentk** [comment]
And I have a todo example started now as well. At the moment it can only create an item.

https://github.com/agentk/ReduxTodoExample
